/** The Chiba Research Group's real rooms and storage units, per the group's
 *  own floor plan and inventory spreadsheet — not a generic placeholder
 *  list. Kept even for units with nothing currently registered, so they
 *  still show up as options when adding a new chemical. */
export const LAB_LOCATIONS = [
  'Lab 1 FC01',
  'Lab 1 FC02',
  'Lab 1 FC03',
  'Lab 1 SC01',
  'Lab 1 SC02',
  'Lab 1 Dry Box 1',
  'Lab 1 Dry Box 2',
  'Lab 1 Fridge 1',
  'Lab 1 Fridge 2',
  'Lab 1 Common',
  'Lab 2 FC02 (Regulated)',
  'Lab 2 FC04',
  'Lab 2 FC05',
  'Lab 2 FC06',
  'Lab 2 FC08',
  'Lab 2 SC01',
  'Lab 2 SC02',
  'Lab 2 Dry Box 1',
  'Lab 2 Dry Box 2',
  'Lab 2 Dry Box 3',
  'Lab 2 Dry Box 4',
  'Lab 2 Dry Box 5',
  'Lab 2 Dry Box 6',
  'Lab 2 Fridge 1',
  'Lab 2 Fridge 2',
  'Lab 2 Fridge 3',
  'Lab 2 Common',
  'Lab 3 FC04',
  'Lab 3 Glovebox',
  'Lab 3 Common',
  'Lab 3 SC01',
  'Lab 3 Acid',
  'Solvent Room SC-01',
  'Chem Store CC-01',
  'Chem Store CC-02',
  'Fridge room Chiba 4°C',
  'Fridge room Yoshikai 4°C',
  'Fridge room Freezer',
  'Fridge room -30°C',
] as const

export const LAB_SUB_LOCATIONS = [
  'Shelf 1 (Top)',
  'Shelf 2',
  'Shelf 3',
  'Shelf 4',
  'Shelf 5',
  'Shelf 6 (Bottom)',
  'Top Shelf',
  'Bottom Shelf',
  'Left side',
  'Right side',
] as const
